# Maxminum length of payload generated by havoc
HAVOC_MAX_LEN = 32

# Master switch for logging information
# This is automatically disabled when -tui option is set
ENABLE_LOG = True

# Flags for logging information
SHOW_FLOW = True
SHOW_STATE = True
SHOW_QUEUE = True
SHOW_PAYLOAD = True

# Filled by arguments - do not manually edit this!
ENABLE_TUI = True