# Maxminum length of payload generated by havoc
HAVOC_MAX_LEN = 32

# Flags for logging information
SHOW_FLOW = True
SHOW_STATE = True
SHOW_QUEUE = True
SHOW_PAYLOAD = True

# Filled by arguments - do not edit!
ENABLE_TUI = False